# 0. 코랩 준비

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip install dpkt -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 195.0/195.0 kB 17.5 MB/s eta 0:00:00

# 1. 12개의 pcap파일 목록

benign파일은 없다.

In [3]:
from pathlib import Path
import pandas as pd

PCAP_DIR = Path("/content/drive/MyDrive/CICIoT2023")

pcap_files = sorted(list(PCAP_DIR.glob("*.pcap")))

print("PCAP 파일 수:", len(pcap_files))

for i, file in enumerate(pcap_files):
    print(i, file.name)

PCAP 파일 수: 12
0 DDoS-ACK_Fragmentation.pcap
1 DDoS-HTTP_Flood-.pcap
2 DDoS-ICMP_Flood.pcap
3 DDoS-ICMP_Fragmentation.pcap
4 DDoS-PSHACK_Flood.pcap
5 DDoS-RSTFINFlood.pcap
6 DDoS-SYN_Flood.pcap
7 DDoS-SlowLoris.pcap
8 DDoS-SynonymousIP_Flood.pcap
9 DDoS-TCP_Flood.pcap
10 DDoS-UDP_Flood.pcap
11 DDoS-UDP_Fragmentation.pcap

# 2. 파일기본정보

단순 파일용량 정리.,필요없

In [4]:
import os

file_info = []

for file in pcap_files:

    file_info.append({
        "file": file.name,
        "size_MB": os.path.getsize(file) / (1024**2)
    })

file_info_df = pd.DataFrame(file_info)

file_info_df

                            file      size_MB
0    DDoS-ACK_Fragmentation.pcap  1953.126059
1          DDoS-HTTP_Flood-.pcap   582.558085
2           DDoS-ICMP_Flood.pcap  1953.125066
3   DDoS-ICMP_Fragmentation.pcap  1953.126064
4         DDoS-PSHACK_Flood.pcap  1953.125021
5          DDoS-RSTFINFlood.pcap  1953.125043
6            DDoS-SYN_Flood.pcap  1953.125060
7            DDoS-SlowLoris.pcap   644.309744
8   DDoS-SynonymousIP_Flood.pcap  1953.125023
9            DDoS-TCP_Flood.pcap  1953.125033
10           DDoS-UDP_Flood.pcap  1953.125058
11   DDoS-UDP_Fragmentation.pcap  1953.125751

# 3. pcap에서 mac/ip/패킷 추출 함수

실질 네트워크 eda

In [5]:
import dpkt
import socket
from collections import defaultdict, Counter


def format_mac(mac_bytes):
    return ":".join(f"{b:02X}" for b in mac_bytes)


def format_ip(ip_bytes):

    try:
        return socket.inet_ntop(socket.AF_INET, ip_bytes)

    except:
        try:
            return socket.inet_ntop(socket.AF_INET6, ip_bytes)
        except:
            return None

In [6]:
#pcap하나 읽어서 기기별 통신량 계산하는 함수

def analyze_pcap_devices(file_path):

    stats = defaultdict(lambda: {
        "sent_packets": 0,
        "received_packets": 0,
        "sent_bytes": 0,
        "received_bytes": 0,
        "ips": set(),
        "peers": Counter()
    })

    f = open(file_path, "rb")

    # pcap / pcapng 둘 다 대응
    try:
        reader = dpkt.pcap.Reader(f)
    except:
        f.seek(0)
        reader = dpkt.pcapng.Reader(f)

    total_packets = 0

    for timestamp, buf in reader:

        try:
            eth = dpkt.ethernet.Ethernet(buf)

            src_mac = format_mac(eth.src)
            dst_mac = format_mac(eth.dst)

            packet_size = len(buf)

            total_packets += 1

            # 송신
            stats[src_mac]["sent_packets"] += 1
            stats[src_mac]["sent_bytes"] += packet_size

            # 수신
            stats[dst_mac]["received_packets"] += 1
            stats[dst_mac]["received_bytes"] += packet_size

            # 상대 기기
            stats[src_mac]["peers"][dst_mac] += 1
            stats[dst_mac]["peers"][src_mac] += 1

            # IPv4
            if isinstance(eth.data, dpkt.ip.IP):

                ip = eth.data

                src_ip = format_ip(ip.src)
                dst_ip = format_ip(ip.dst)

                stats[src_mac]["ips"].add(src_ip)
                stats[dst_mac]["ips"].add(dst_ip)

            # IPv6
            elif isinstance(eth.data, dpkt.ip6.IP6):

                ip = eth.data

                src_ip = format_ip(ip.src)
                dst_ip = format_ip(ip.dst)

                stats[src_mac]["ips"].add(src_ip)
                stats[dst_mac]["ips"].add(dst_ip)

        except:
            continue

    f.close()

    rows = []

    for mac, s in stats.items():

        total = (
            s["sent_packets"]
            + s["received_packets"]
        )

        total_bytes = (
            s["sent_bytes"]
            + s["received_bytes"]
        )

        if len(s["peers"]) > 0:
            top_peer, top_peer_packets = s["peers"].most_common(1)[0]
        else:
            top_peer = None
            top_peer_packets = 0

        rows.append({
            "mac": mac,
            "ips": ", ".join(sorted(x for x in s["ips"] if x)),
            "sent_packets": s["sent_packets"],
            "received_packets": s["received_packets"],
            "total_packets": total,
            "sent_bytes": s["sent_bytes"],
            "received_bytes": s["received_bytes"],
            "total_bytes": total_bytes,
            "unique_peers": len(s["peers"]),
            "top_peer": top_peer,
            "top_peer_packets": top_peer_packets
        })

    df = pd.DataFrame(rows)

    df = df.sort_values(
        "total_packets",
        ascending=False
    )

    return total_packets, df

# 4. pcap하나 먼저 확인

In [7]:
file = pcap_files[0]

total_packets, device_df = analyze_pcap_devices(file)

print("파일:", file.name)
print("전체 패킷:", total_packets)

device_df.head(20)

파일: DDoS-ACK_Fragmentation.pcap
전체 패킷: 2503835

,mac,ips,sent_packets,received_packets,total_packets,sent_bytes,received_bytes,total_bytes,unique_peers,top_peer,top_peer_packets
77,B0:C5:54:59:2E:99,192.168.137.132,8278,878305,886583,516304,826686739,827203043,9,DC:A6:32:C9:E4:AB,221817
68,8C:85:80:6C:B6:47,"192.168.137.123, fe80::8e85:80ff:fe6c:b647",268504,544412,812916,16137169,512315019,528452188,11,DC:A6:32:DC:27:D5,339968
63,DC:A6:32:C9:E4:AB,"0.0.0.0, 192.168.137.196, fd5a:7bd:2aea:e111:d...",555586,56391,611977,522916337,3384066,526300403,9,B0:C5:54:59:2E:99,221817
59,DC:A6:32:DC:27:D5,"0.0.0.0, 192.168.137.65, fd5a:7bd:2aea:e111:de...",486229,114608,600837,457526433,6877616,464404049,9,8C:85:80:6C:B6:47,339968
58,9C:8E:CD:1D:AB:9F,192.168.137.120,12678,564673,577351,1181940,530046438,531228378,9,DC:A6:32:C9:E4:AB,206525
64,DC:A6:32:C9:E4:90,"0.0.0.0, 192.168.137.17, fe80::dea6:32ff:fec9:...",360659,31348,392007,339201719,1882016,341083735,8,B0:C5:54:59:2E:99,187388
62,DC:A6:32:C9:E5:EF,"0.0.0.0, 192.168.137.42, fd5a:7bd:2aea:e111:de...",268720,27981,296701,252612449,1679958,254292407,9,B0:C5:54:59:2E:99,136301
65,E4:5F:01:55:90:C4,"0.0.0.0, 192.168.137.12, fd5a:7bd:2aea:e111:e6...",196733,26868,223601,184786226,1772178,186558404,9,B0:C5:54:59:2E:99,87632
60,DC:A6:32:C9:E4:D5,"0.0.0.0, 192.168.137.20, fd5a:7bd:2aea:e111:de...",129808,14235,144043,121638615,854668,122493283,9,9C:8E:CD:1D:AB:9F,49013
61,DC:A6:32:C9:E5:A4,"0.0.0.0, 192.168.137.186, fe80::dea6:32ff:fec9...",86639,12595,99234,80913576,755738,81669314,8,B0:C5:54:59:2E:99,40354
37,50:02:91:B1:68:0C,"192.168.137.223, ::",419,96547,96966,47847,90719753,90767600,11,DC:A6:32:C9:E4:AB,27397
0,3C:18:A0:41:C3:A0,"1.0.0.1, 1.1.1.1, 100.20.110.248, 100.20.212.2...",43390,39093,82483,9842922,16430182,26273104,62,40:5D:82:35:14:C8,13169
25,A0:D0:DC:C4:08:FF,192.168.137.210,15045,13564,28609,1052226,1012864,2065090,5,2C:71:FF:05:F1:15,14100
4,FF:FF:FF:FF:FF:FF,"192.168.137.255, 255.255.255.255",0,23236,23236,0,2195410,2195410,68,AC:F1:08:4E:00:82,2252
24,2C:71:FF:05:F1:15,"0.0.0.0, 192.168.137.75, ::, fe80::2e71:ffff:f...",8797,8685,17482,1071090,951633,2022723,11,A0:D0:DC:C4:08:FF,14100
27,1C:FE:2B:98:16:DD,192.168.137.233,7434,7099,14533,611597,1030096,1641693,5,A0:D0:DC:C4:08:FF,10653
48,40:5D:82:35:14:C8,192.168.137.51,7020,6290,13310,7900900,1073707,8974607,2,3C:18:A0:41:C3:A0,13169
2,44:BB:3B:00:39:07,"0.0.0.0, 192.168.137.149",3177,2834,6011,1709483,206408,1915891,3,3C:18:A0:41:C3:A0,5951
87,AC:F1:08:4E:00:82,192.168.137.145,3908,1749,5657,360092,450510,810602,5,3C:18:A0:41:C3:A0,3060
45,08:7C:39:CE:6E:2A,"0.0.0.0, 192.168.137.162, ::, fe80::a7c:39ff:f...",2785,2811,5596,445734,321301,767035,10,A0:D0:DC:C4:08:FF,2975

In [8]:
#FF:FF:FF:FF:FF:FF같은 broadcast mac는 기기가 아니니 제외하기
device_df = device_df[
    device_df["mac"] != "FF:FF:FF:FF:FF:FF"
]

device_df.head(20)

,mac,ips,sent_packets,received_packets,total_packets,sent_bytes,received_bytes,total_bytes,unique_peers,top_peer,top_peer_packets
77,B0:C5:54:59:2E:99,192.168.137.132,8278,878305,886583,516304,826686739,827203043,9,DC:A6:32:C9:E4:AB,221817
68,8C:85:80:6C:B6:47,"192.168.137.123, fe80::8e85:80ff:fe6c:b647",268504,544412,812916,16137169,512315019,528452188,11,DC:A6:32:DC:27:D5,339968
63,DC:A6:32:C9:E4:AB,"0.0.0.0, 192.168.137.196, fd5a:7bd:2aea:e111:d...",555586,56391,611977,522916337,3384066,526300403,9,B0:C5:54:59:2E:99,221817
59,DC:A6:32:DC:27:D5,"0.0.0.0, 192.168.137.65, fd5a:7bd:2aea:e111:de...",486229,114608,600837,457526433,6877616,464404049,9,8C:85:80:6C:B6:47,339968
58,9C:8E:CD:1D:AB:9F,192.168.137.120,12678,564673,577351,1181940,530046438,531228378,9,DC:A6:32:C9:E4:AB,206525
64,DC:A6:32:C9:E4:90,"0.0.0.0, 192.168.137.17, fe80::dea6:32ff:fec9:...",360659,31348,392007,339201719,1882016,341083735,8,B0:C5:54:59:2E:99,187388
62,DC:A6:32:C9:E5:EF,"0.0.0.0, 192.168.137.42, fd5a:7bd:2aea:e111:de...",268720,27981,296701,252612449,1679958,254292407,9,B0:C5:54:59:2E:99,136301
65,E4:5F:01:55:90:C4,"0.0.0.0, 192.168.137.12, fd5a:7bd:2aea:e111:e6...",196733,26868,223601,184786226,1772178,186558404,9,B0:C5:54:59:2E:99,87632
60,DC:A6:32:C9:E4:D5,"0.0.0.0, 192.168.137.20, fd5a:7bd:2aea:e111:de...",129808,14235,144043,121638615,854668,122493283,9,9C:8E:CD:1D:AB:9F,49013
61,DC:A6:32:C9:E5:A4,"0.0.0.0, 192.168.137.186, fe80::dea6:32ff:fec9...",86639,12595,99234,80913576,755738,81669314,8,B0:C5:54:59:2E:99,40354
37,50:02:91:B1:68:0C,"192.168.137.223, ::",419,96547,96966,47847,90719753,90767600,11,DC:A6:32:C9:E4:AB,27397
0,3C:18:A0:41:C3:A0,"1.0.0.1, 1.1.1.1, 100.20.110.248, 100.20.212.2...",43390,39093,82483,9842922,16430182,26273104,62,40:5D:82:35:14:C8,13169
25,A0:D0:DC:C4:08:FF,192.168.137.210,15045,13564,28609,1052226,1012864,2065090,5,2C:71:FF:05:F1:15,14100
24,2C:71:FF:05:F1:15,"0.0.0.0, 192.168.137.75, ::, fe80::2e71:ffff:f...",8797,8685,17482,1071090,951633,2022723,11,A0:D0:DC:C4:08:FF,14100
27,1C:FE:2B:98:16:DD,192.168.137.233,7434,7099,14533,611597,1030096,1641693,5,A0:D0:DC:C4:08:FF,10653
48,40:5D:82:35:14:C8,192.168.137.51,7020,6290,13310,7900900,1073707,8974607,2,3C:18:A0:41:C3:A0,13169
2,44:BB:3B:00:39:07,"0.0.0.0, 192.168.137.149",3177,2834,6011,1709483,206408,1915891,3,3C:18:A0:41:C3:A0,5951
87,AC:F1:08:4E:00:82,192.168.137.145,3908,1749,5657,360092,450510,810602,5,3C:18:A0:41:C3:A0,3060
45,08:7C:39:CE:6E:2A,"0.0.0.0, 192.168.137.162, ::, fe80::a7c:39ff:f...",2785,2811,5596,445734,321301,767035,10,A0:D0:DC:C4:08:FF,2975
51,56:4F:8A:E1:F3:2D,"0.0.0.0, 192.168.137.150, ::, fe80::c5b:11f4:4...",2717,2438,5155,329859,2236581,2566440,10,3C:18:A0:41:C3:A0,4841

# 5. 카메라 MAC을 실제 이름으로 매핑

In [9]:
CAMERA_MAP = {

    "9C:8E:CD:1D:AB:9F":
        "AMCREST WiFi Camera",

    "3C:37:86:6F:B9:51":
        "Arlo Base Station",

    "40:5D:82:35:14:C8":
        "Arlo Q Indoor Camera",

    "C0:E7:BF:0A:79:D1":
        "Borun/Sichuan-AI Camera",

    "B0:C5:54:59:2E:99":
        "D-Link Mini Camera",

    "44:01:BB:EC:10:4A":
        "HeimVision Smart WiFi Camera",

    "34:75:63:73:F3:36":
        "Home Eye Camera",

    "7C:A7:B0:CD:18:32":
        "Luohe Cam Dog",

    "44:BB:3B:00:39:07":
        "Nest Indoor Camera",

    "70:EE:50:68:0E:32":
        "Netatmo Camera",

    "10:5A:17:97:A5:C6":
        "Rbcior Camera",

    "10:2C:6B:1B:43:BE":
        "SIMCAM 1S",

    "6C:5A:B0:44:1D:90":
        "TP-Link Tapo Camera",

    "7C:78:B2:86:0D:81":
        "Wyze Camera",

    "84:7A:B6:64:62:58":
        "Yi Indoor Camera",

    "84:7A:B6:62:3A:6C":
        "Yi Indoor 2 Camera",

    "2C:D2:6B:66:D2:87":
        "Yi Outdoor Camera"
}

#해당 pcap에서 어떤 카메라가 얼마나 많이 통신했는지 확인
device_df["camera_name"] = device_df["mac"].map(CAMERA_MAP)

camera_df = device_df[
    device_df["camera_name"].notna()
]

camera_df[
    [
        "camera_name",
        "mac",
        "ips",
        "sent_packets",
        "received_packets",
        "total_packets",
        "total_bytes",
        "top_peer"
    ]
]

,camera_name,mac,ips,sent_packets,received_packets,total_packets,total_bytes,top_peer
77,D-Link Mini Camera,B0:C5:54:59:2E:99,192.168.137.132,8278,878305,886583,827203043,DC:A6:32:C9:E4:AB
58,AMCREST WiFi Camera,9C:8E:CD:1D:AB:9F,192.168.137.120,12678,564673,577351,531228378,DC:A6:32:C9:E4:AB
48,Arlo Q Indoor Camera,40:5D:82:35:14:C8,192.168.137.51,7020,6290,13310,8974607,3C:18:A0:41:C3:A0
2,Nest Indoor Camera,44:BB:3B:00:39:07,"0.0.0.0, 192.168.137.149",3177,2834,6011,1915891,3C:18:A0:41:C3:A0
47,Netatmo Camera,70:EE:50:68:0E:32,"0.0.0.0, 192.168.137.48, ::, fe80::72ee:50ff:f...",2880,2163,5043,3250963,3C:18:A0:41:C3:A0
1,HeimVision Smart WiFi Camera,44:01:BB:EC:10:4A,192.168.137.131,1430,761,2191,281445,3C:18:A0:41:C3:A0
17,Wyze Camera,7C:78:B2:86:0D:81,"0.0.0.0, 192.168.137.200",1177,782,1959,348353,3C:18:A0:41:C3:A0
57,TP-Link Tapo Camera,6C:5A:B0:44:1D:90,192.168.137.187,1014,811,1825,221768,3C:18:A0:41:C3:A0
26,SIMCAM 1S,10:2C:6B:1B:43:BE,192.168.137.179,854,790,1644,123823,3C:18:A0:41:C3:A0
39,Home Eye Camera,34:75:63:73:F3:36,192.168.137.173,901,658,1559,113405,3C:18:A0:41:C3:A0
6,Rbcior Camera,10:5A:17:97:A5:C6,"0.0.0.0, 192.168.137.211",828,561,1389,147151,FF:FF:FF:FF:FF:FF
30,Yi Indoor Camera,84:7A:B6:64:62:58,192.168.137.118,526,496,1022,113455,3C:18:A0:41:C3:A0
9,Borun/Sichuan-AI Camera,C0:E7:BF:0A:79:D1,"0.0.0.0, 192.168.137.163",676,222,898,80630,3C:18:A0:41:C3:A0
41,Arlo Base Station,3C:37:86:6F:B9:51,"192.168.137.76, fe80::3e37:86ff:fe6f:b951",494,397,891,160165,3C:18:A0:41:C3:A0
31,Yi Outdoor Camera,2C:D2:6B:66:D2:87,192.168.137.205,437,436,873,61542,3C:18:A0:41:C3:A0
46,Yi Indoor 2 Camera,84:7A:B6:62:3A:6C,192.168.137.66,380,369,749,72176,3C:18:A0:41:C3:A0
56,Luohe Cam Dog,7C:A7:B0:CD:18:32,192.168.137.140,295,231,526,36899,3C:18:A0:41:C3:A0

# 6. 12개 파일전부 분석

In [19]:
all_device_results = []

for file in pcap_files:

    print("분석중:", file.name)

    total_packets, temp_df = analyze_pcap_devices(file)

    temp_df["file"] = file.name

    all_device_results.append(temp_df)


all_devices_df = pd.concat(
    all_device_results,
    ignore_index=True
)

분석중: DDoS-ACK_Fragmentation.pcap
분석중: DDoS-HTTP_Flood-.pcap
분석중: DDoS-ICMP_Flood.pcap
분석중: DDoS-ICMP_Fragmentation.pcap
분석중: DDoS-PSHACK_Flood.pcap
분석중: DDoS-RSTFINFlood.pcap
분석중: DDoS-SYN_Flood.pcap
분석중: DDoS-SlowLoris.pcap
분석중: DDoS-SynonymousIP_Flood.pcap
분석중: DDoS-TCP_Flood.pcap
분석중: DDoS-UDP_Flood.pcap
분석중: DDoS-UDP_Fragmentation.pcap

all_devices_df까지 만든 후 각 공격 파일에서 가장 많이 패킷 받은 top5확인하기.
12개 파일 모두 ddos공격이고 benign파일이 하나도 없다 ->공식CICIoT2023 설명에도
DDoS 유형으로 ACK Fragmentation, UDP Flood, SlowLoris, ICMP Flood, RSTFIN Flood, PSHACK Flood, HTTP Flood, UDP Fragmentation, TCP Flood, SYN Flood, SynonymousIP Flood 등이
포함되어 있는데, 내 폴더는 여기에 ICMP Fragmentation까지 포함된 ddos공격 묶음.

그래서 이 12개파일만 가지로 ddos인지 정상인지를 rf로 학습 못함. 왜냐? 전무 정답이 ddos=1 인셈.


## 1단계 — 지금 가진 DDoS PCAP 12개로 네트워크 구조 EDA
는 그대로 진행하기.

목표는
각 공격 PCAP   
 ↓   
어떤 MAC들이 등장했는가?   
 ↓   
각 MAC은 어떤 IP를 사용했는가?   
 ↓   
송신/수신 packet 수   
 ↓   
어떤 상대와 가장 많이 통신했는가?   
 ↓   
실제 IoT 기기 이름과 MAC 매칭   
 ↓   
공격별 가장 통신량 많은 기기 확인   

즉, analyze_pcap_devices() 코드부터 실행


단, 가장 많이 등장하는 mac= 가장 많이 공격받은 iot기기 라고 단정 x :  ddos에서는 공격자 기기들의 트래픽도 매우 많을 수 있음

그래서 피해기기만 찾기 위해 received_packets순위를 확인해야함.

In [20]:
top_received_per_file = (
    all_devices_df
    .sort_values(
        ["file", "received_packets"],
        ascending=[True, False]
    )
    .groupby("file")
    .head(5)
)

#각 공격 파일에서 가장 많이 패킷 받은 mac top 5나옴
top_received_per_file[
    [
        "file",
        "mac",
        "ips",
        "sent_packets",
        "received_packets",
        "total_packets"
    ]
]

,file,mac,ips,sent_packets,received_packets,total_packets
0,DDoS-ACK_Fragmentation.pcap,B0:C5:54:59:2E:99,192.168.137.132,8278,878305,886583
4,DDoS-ACK_Fragmentation.pcap,9C:8E:CD:1D:AB:9F,192.168.137.120,12678,564673,577351
1,DDoS-ACK_Fragmentation.pcap,8C:85:80:6C:B6:47,"192.168.137.123, fe80::8e85:80ff:fe6c:b647",268504,544412,812916
3,DDoS-ACK_Fragmentation.pcap,DC:A6:32:DC:27:D5,"0.0.0.0, 192.168.137.65, fd5a:7bd:2aea:e111:de...",486229,114608,600837
10,DDoS-ACK_Fragmentation.pcap,50:02:91:B1:68:0C,"192.168.137.223, ::",419,96547,96966
108,DDoS-HTTP_Flood-.pcap,9C:8E:CD:1D:AB:9F,"0.0.0.0, 192.168.137.139, 192.168.137.86",212128,475270,687398
109,DDoS-HTTP_Flood-.pcap,DC:A6:32:DC:27:D5,"192.168.137.178, 192.168.137.82, fe80::dea6:32...",197686,394220,591906
115,DDoS-HTTP_Flood-.pcap,DC:A6:32:C9:E5:A4,"192.168.137.186, 192.168.137.60, fe80::dea6:32...",40788,296704,337492
111,DDoS-HTTP_Flood-.pcap,DC:A6:32:C9:E4:90,"192.168.137.17, 192.168.137.238, fe80::dea6:32...",100548,278364,378912
112,DDoS-HTTP_Flood-.pcap,E4:5F:01:55:90:C4,"192.168.137.12, 192.168.137.89, fe80::e65f:1ff...",113287,261000,374287
227,DDoS-ICMP_Flood.pcap,1C:FE:2B:98:16:DD,"0.0.0.0, 192.168.137.254",2280,15787965,15790245
228,DDoS-ICMP_Flood.pcap,1C:12:B0:9B:0C:EC,"0.0.0.0, 192.168.137.37, ::, fe80::1e12:b0ff:f...",9004,10893507,10902511
236,DDoS-ICMP_Flood.pcap,3C:18:A0:41:C3:A0,"1.1.1.1, 100.20.212.253, 100.21.15.118, 104.12...",43094,36447,79541
238,DDoS-ICMP_Flood.pcap,FF:FF:FF:FF:FF:FF,255.255.255.255,0,22299,22299
237,DDoS-ICMP_Flood.pcap,AC:17:02:05:34:27,192.168.137.94,11326,11248,22574
322,DDoS-ICMP_Fragmentation.pcap,1C:FE:2B:98:16:DD,"0.0.0.0, 192.168.137.100",3629,790754,794383
323,DDoS-ICMP_Fragmentation.pcap,CC:F4:11:9C:D0:00,"0.0.0.0, 192.168.137.134, ::, fe80::cef4:11ff:...",13322,582768,596090
324,DDoS-ICMP_Fragmentation.pcap,1C:12:B0:9B:0C:EC,"0.0.0.0, 192.168.137.206, ::, fe80::1e12:b0ff:...",3439,550389,553828
332,DDoS-ICMP_Fragmentation.pcap,3C:18:A0:41:C3:A0,"1.0.0.1, 1.1.1.1, 100.20.110.248, 100.20.212.2...",49297,46717,96014
333,DDoS-ICMP_Fragmentation.pcap,FF:FF:FF:FF:FF:FF,255.255.255.255,0,28148,28148
429,DDoS-PSHACK_Flood.pcap,1C:FE:2B:98:16:DD,"0.0.0.0, 192.168.137.233",187054,12994828,13181882
430,DDoS-PSHACK_Flood.pcap,1C:12:B0:9B:0C:EC,"0.0.0.0, 192.168.137.206, ::, fe80::1e12:b0ff:...",164314,11382204,11546518
438,DDoS-PSHACK_Flood.pcap,9C:8E:CD:1D:AB:9F,192.168.137.120,5119,1960013,1965132
431,DDoS-PSHACK_Flood.pcap,DC:A6:32:C9:E5:A4,"192.168.137.186, fdcc:d8dd:e1af:26ab:dea6:32ff...",5235887,77625,5313512
434,DDoS-PSHACK_Flood.pcap,DC:A6:32:DC:27:D5,"192.168.137.65, fe80::dea6:32ff:fedc:27d5",3428643,52806,3481449
530,DDoS-RSTFINFlood.pcap,1C:FE:2B:98:16:DD,"0.0.0.0, 192.168.137.5",2363,12575492,12577855
531,DDoS-RSTFINFlood.pcap,28:6D:97:9E:F4:D5,"0.0.0.0, 192.168.137.250, ::, fd5a:7bd:2aea:e1...",1056,11989659,11990715
539,DDoS-RSTFINFlood.pcap,2C:71:FF:05:F1:15,"0.0.0.0, 192.168.137.85, ::, fe80::2e71:ffff:f...",1660,2023560,2025220
540,DDoS-RSTFINFlood.pcap,3C:18:A0:41:C3:A0,"1.0.0.1, 1.1.1.1, 100.20.110.248, 100.20.212.2...",40357,33715,74072
541,DDoS-RSTFINFlood.pcap,FF:FF:FF:FF:FF:FF,255.255.255.255,0,17824,17824
632,DDoS-SYN_Flood.pcap,1C:12:B0:9B:0C:EC,"0.0.0.0, 192.168.137.99, ::, fe80::1e12:b0ff:f...",170629,8786693,8957322
633,DDoS-SYN_Flood.pcap,1C:FE:2B:98:16:DD,"0.0.0.0, 192.168.137.30",223059,7655917,7878976
635,DDoS-SYN_Flood.pcap,CC:F4:11:9C:D0:00,"0.0.0.0, 192.168.137.12, ::, fe80::cef4:11ff:f...",5618,6701211,6706829
641,DDoS-SYN_Flood.pcap,9C:8E:CD:1D:AB:9F,192.168.137.161,14686,2870769,2885455
634,DDoS-SYN_Flood.pcap,DC:A6:32:C9:E4:AB,"192.168.137.240, fe80::dea6:32ff:fec9:e4ab",7079462,87516,7166978
734,DDoS-SlowLoris.pcap,3C:18:A0:41:C3:A0,"1.0.0.1, 1.1.1.1, 100.20.212.253, 100.20.83.2,...",376053,411558,787611
735,DDoS-SlowLoris.pcap,40:5D:82:35:14:C8,192.168.137.210,183985,162541,346526
736,DDoS-SlowLoris.pcap,B0:C5:54:59:2E:99,192.168.137.236,143303,144434,287737
737,DDoS-SlowLoris.pcap,6C:5A:B0:44:1D:90,192.168.137.29,139306,141488,280794
738,DDoS-SlowLoris.pcap,DC:A6:32:DC:27:D5,"0.0.0.0, 192.168.137.82, fd5a:7bd:2aea:e111:de...",117758,103300,221058
831,DDoS-SynonymousIP_Flood.pcap,2C:71:FF:05:F1:15,192.168.137.247,2546,12909807,12912353
832,DDoS-SynonymousIP_Flood.pcap,9C:8E:CD:1D:AB:9F,192.168.137.86,1054,12032654,12033708
839,DDoS-SynonymousIP_Flood.pcap,8C:85:80:6C:B6:47,"192.168.137.123, fe80::8e85:80ff:fe6c:b647",841,1853342,1854183
841,DDoS-SynonymousIP_Flood.pcap,3C:18:A0:41:C3:A0,"1.0.0.1, 1.1.1.1, 100.20.212.253, 100.20.83.2,...",24108,19404,43512
842,DDoS-SynonymousIP_Flood.pcap,FF:FF:FF:FF:FF:FF,"192.168.137.255, 255.255.255.255",0,14359,14359
919,DDoS-TCP_Flood.pcap,1C:FE:2B:98:16:DD,"0.0.0.0, 192.168.137.123",3833,14702613,14706446
920,DDoS-TCP_Flood.pcap,1C:12:B0:9B:0C:EC,"0.0.0.0, 192.168.137.99, ::, fe80::1e12:b0ff:f...",2569,7428510,7431079
922,DDoS-TCP_Flood.pcap,A0:D0:DC:C4:08:FF,"0.0.0.0, 192.168.137.96",6130,4289589,4295719
929,DDoS-TCP_Flood.pcap,3C:18:A0:41:C3:A0,"1.0.0.1, 1.1.1.1, 100.20.110.248, 100.20.126.2...",64476,62746,127222
931,DDoS-TCP_Flood.pcap,FF:FF:FF:FF:FF:FF,"0.0.0.0, 255.255.255.255",0,20497,20497
1024,DDoS-UDP_Flood.pcap,1C:FE:2B:98:16:DD,"0.0.0.0, 192.168.137.247, 192.168.137.30",7075,13541168,13548243
1025,DDoS-UDP_Flood.pcap,1C:12:B0:9B:0C:EC,"0.0.0.0, 192.168.137.99, ::, fe80::1e12:b0ff:f...",3873,9105800,9109673
1029,DDoS-UDP_Flood.pcap,A0:D0:DC:C4:08:FF,"0.0.0.0, 192.168.137.14",5926,3859789,3865715
1034,DDoS-UDP_Flood.pcap,3C:18:A0:41:C3:A0,"1.1.1.1, 100.20.212.253, 100.21.156.247, 100.2...",59782,54313,114095
1036,DDoS-UDP_Flood.pcap,FF:FF:FF:FF:FF:FF,255.255.255.255,0,22187,22187
1122,DDoS-UDP_Fragmentation.pcap,28:6D:97:9E:F4:D5,"0.0.0.0, 192.168.137.79, ::, fd5a:7bd:2aea:e11...",5000,797763,802763
1123,DDoS-UDP_Fragmentation.pcap,1C:FE:2B:98:16:DD,"0.0.0.0, 192.168.137.90",8605,734536,743141
1126,DDoS-UDP_Fragmentation.pcap,2C:71:FF:05:F1:15,"0.0.0.0, 192.168.137.247, ::, fe80::2e71:ffff:...",4462,411284,415746
1129,DDoS-UDP_Fragmentation.pcap,9C:8E:CD:1D:AB:9F,"0.0.0.0, 192.168.137.86",3022,186934,189956
1133,DDoS-UDP_Fragmentation.pcap,3C:18:A0:41:C3:A0,"1.0.0.1, 1.1.1.1, 100.20.212.253, 100.21.15.11...",41636,36254,77890

In [21]:
# 반대로 송신량을 위에랑 비교해야함->비교로 많이 통신한 것 구별하기. !!!!!!

top_sent_per_file = (
    all_devices_df
    .sort_values(
        ["file", "sent_packets"],
        ascending=[True, False]
    )
    .groupby("file")
    .head(5)
)

top_sent_per_file[
    [
        "file",
        "mac",
        "ips",
        "sent_packets",
        "received_packets",
        "total_packets"
    ]
]

,file,mac,ips,sent_packets,received_packets,total_packets
2,DDoS-ACK_Fragmentation.pcap,DC:A6:32:C9:E4:AB,"0.0.0.0, 192.168.137.196, fd5a:7bd:2aea:e111:d...",555586,56391,611977
3,DDoS-ACK_Fragmentation.pcap,DC:A6:32:DC:27:D5,"0.0.0.0, 192.168.137.65, fd5a:7bd:2aea:e111:de...",486229,114608,600837
5,DDoS-ACK_Fragmentation.pcap,DC:A6:32:C9:E4:90,"0.0.0.0, 192.168.137.17, fe80::dea6:32ff:fec9:...",360659,31348,392007
6,DDoS-ACK_Fragmentation.pcap,DC:A6:32:C9:E5:EF,"0.0.0.0, 192.168.137.42, fd5a:7bd:2aea:e111:de...",268720,27981,296701
1,DDoS-ACK_Fragmentation.pcap,8C:85:80:6C:B6:47,"192.168.137.123, fe80::8e85:80ff:fe6c:b647",268504,544412,812916
114,DDoS-HTTP_Flood-.pcap,B0:F1:EC:D3:E7:98,"0.0.0.0, 192.168.137.150, fe80::b2f1:ecff:fed3...",341724,0,341724
117,DDoS-HTTP_Flood-.pcap,DC:A6:32:C9:E5:02,"0.0.0.0, 192.168.137.134, 192.168.137.44, fd5a...",291356,9,291365
119,DDoS-HTTP_Flood-.pcap,DC:A6:32:C9:E4:C6,"0.0.0.0, 192.168.137.133, 192.168.137.156, ::,...",280682,3,280685
120,DDoS-HTTP_Flood-.pcap,DC:A6:32:C9:E6:F4,"0.0.0.0, 192.168.137.114, 192.168.137.147, fd5...",271981,4,271985
108,DDoS-HTTP_Flood-.pcap,9C:8E:CD:1D:AB:9F,"0.0.0.0, 192.168.137.139, 192.168.137.86",212128,475270,687398
229,DDoS-ICMP_Flood.pcap,DC:A6:32:DC:27:D5,192.168.137.198,4753338,1244,4754582
230,DDoS-ICMP_Flood.pcap,DC:A6:32:C9:E5:A4,192.168.137.108,4495002,1381,4496383
231,DDoS-ICMP_Flood.pcap,E4:5F:01:55:90:C4,192.168.137.214,4244031,1115,4245146
232,DDoS-ICMP_Flood.pcap,DC:A6:32:C9:E5:EF,"192.168.137.81, fe80::dea6:32ff:fec9:e5ef",4196879,705,4197584
233,DDoS-ICMP_Flood.pcap,DC:A6:32:C9:E4:D5,"192.168.137.23, fe80::dea6:32ff:fec9:e4d5",4191590,513,4192103
325,DDoS-ICMP_Fragmentation.pcap,DC:A6:32:C9:E5:A4,"192.168.137.127, fe80::dea6:32ff:fec9:e5a4",394462,1655,396117
326,DDoS-ICMP_Fragmentation.pcap,E4:5F:01:55:90:C4,"192.168.137.22, fe80::e65f:1ff:fe55:90c4",357008,1972,358980
327,DDoS-ICMP_Fragmentation.pcap,DC:A6:32:C9:E4:AB,"192.168.137.27, fe80::dea6:32ff:fec9:e4ab",347052,2143,349195
328,DDoS-ICMP_Fragmentation.pcap,DC:A6:32:C9:E4:D5,"192.168.137.64, fe80::dea6:32ff:fec9:e4d5",254412,1560,255972
329,DDoS-ICMP_Fragmentation.pcap,DC:A6:32:C9:E5:EF,"192.168.137.151, fe80::dea6:32ff:fec9:e5ef",229161,1244,230405
431,DDoS-PSHACK_Flood.pcap,DC:A6:32:C9:E5:A4,"192.168.137.186, fdcc:d8dd:e1af:26ab:dea6:32ff...",5235887,77625,5313512
432,DDoS-PSHACK_Flood.pcap,DC:A6:32:C9:E4:AB,"192.168.137.196, fdcc:d8dd:e1af:26ab:dea6:32ff...",4637726,48121,4685847
433,DDoS-PSHACK_Flood.pcap,DC:A6:32:C9:E4:90,"192.168.137.17, fdcc:d8dd:e1af:26ab:dea6:32ff:...",3901568,48093,3949661
434,DDoS-PSHACK_Flood.pcap,DC:A6:32:DC:27:D5,"192.168.137.65, fe80::dea6:32ff:fedc:27d5",3428643,52806,3481449
435,DDoS-PSHACK_Flood.pcap,DC:A6:32:C9:E4:D5,"192.168.137.20, fdcc:d8dd:e1af:26ab:dea6:32ff:...",3250113,44535,3294648
532,DDoS-RSTFINFlood.pcap,DC:A6:32:DC:27:D5,192.168.137.65,4745664,29,4745693
533,DDoS-RSTFINFlood.pcap,DC:A6:32:C9:E5:A4,192.168.137.186,4356533,30,4356563
534,DDoS-RSTFINFlood.pcap,DC:A6:32:C9:E4:D5,"192.168.137.20, fd5a:7bd:2aea:e111:dea6:32ff:f...",3931508,34,3931542
535,DDoS-RSTFINFlood.pcap,E4:5F:01:55:90:C4,"192.168.137.12, fd5a:7bd:2aea:e111:e65f:1ff:fe...",3919801,36,3919837
536,DDoS-RSTFINFlood.pcap,DC:A6:32:C9:E4:90,"0.0.0.0, 192.168.137.17, fe80::dea6:32ff:fec9:...",3389510,27,3389537
634,DDoS-SYN_Flood.pcap,DC:A6:32:C9:E4:AB,"192.168.137.240, fe80::dea6:32ff:fec9:e4ab",7079462,87516,7166978
636,DDoS-SYN_Flood.pcap,DC:A6:32:DC:27:D5,"192.168.137.17, fe80::dea6:32ff:fedc:27d5",4307275,70868,4378143
637,DDoS-SYN_Flood.pcap,DC:A6:32:C9:E4:90,192.168.137.195,4163427,64320,4227747
638,DDoS-SYN_Flood.pcap,E4:5F:01:55:90:C4,192.168.137.134,3827597,60845,3888442
639,DDoS-SYN_Flood.pcap,DC:A6:32:C9:E5:EF,"192.168.137.58, fe80::dea6:32ff:fec9:e5ef",3659456,56798,3716254
734,DDoS-SlowLoris.pcap,3C:18:A0:41:C3:A0,"1.0.0.1, 1.1.1.1, 100.20.212.253, 100.20.83.2,...",376053,411558,787611
735,DDoS-SlowLoris.pcap,40:5D:82:35:14:C8,192.168.137.210,183985,162541,346526
736,DDoS-SlowLoris.pcap,B0:C5:54:59:2E:99,192.168.137.236,143303,144434,287737
737,DDoS-SlowLoris.pcap,6C:5A:B0:44:1D:90,192.168.137.29,139306,141488,280794
738,DDoS-SlowLoris.pcap,DC:A6:32:DC:27:D5,"0.0.0.0, 192.168.137.82, fd5a:7bd:2aea:e111:de...",117758,103300,221058
833,DDoS-SynonymousIP_Flood.pcap,DC:A6:32:C9:E4:AB,"192.168.137.123, 192.168.137.212, 192.168.137....",7855183,27,7855210
834,DDoS-SynonymousIP_Flood.pcap,DC:A6:32:C9:E4:90,"192.168.137.123, 192.168.137.17, 192.168.137.2...",5342461,26,5342487
835,DDoS-SynonymousIP_Flood.pcap,DC:A6:32:C9:E5:EF,"192.168.137.123, 192.168.137.247, 192.168.137....",3141716,29,3141745
836,DDoS-SynonymousIP_Flood.pcap,DC:A6:32:C9:E5:A4,"192.168.137.123, 192.168.137.186, 192.168.137....",3052290,31,3052321
837,DDoS-SynonymousIP_Flood.pcap,E4:5F:01:55:90:C4,"192.168.137.12, 192.168.137.123, 192.168.137.2...",3024878,28,3024906
921,DDoS-TCP_Flood.pcap,DC:A6:32:DC:27:D5,"192.168.137.17, fe80::dea6:32ff:fedc:27d5",6170232,709,6170941
923,DDoS-TCP_Flood.pcap,DC:A6:32:C9:E4:D5,192.168.137.15,4191762,30,4191792
924,DDoS-TCP_Flood.pcap,DC:A6:32:C9:E5:EF,"192.168.137.156, fe80::dea6:32ff:fec9:e5ef",3678970,29,3678999
925,DDoS-TCP_Flood.pcap,DC:A6:32:C9:E4:AB,"192.168.137.178, fe80::dea6:32ff:fec9:e4ab",3433848,31,3433879
926,DDoS-TCP_Flood.pcap,DC:A6:32:C9:E4:90,"192.168.137.195, fe80::dea6:32ff:fec9:e490",3330284,29,3330313
1026,DDoS-UDP_Flood.pcap,E4:5F:01:55:90:C4,"192.168.137.134, fe80::e65f:1ff:fe55:90c4",4099560,845,4100405
1027,DDoS-UDP_Flood.pcap,DC:A6:32:C9:E4:AB,192.168.137.240,4077920,927,4078847
1028,DDoS-UDP_Flood.pcap,DC:A6:32:DC:27:D5,"192.168.137.17, 192.168.137.198, fe80::dea6:32...",3920113,1640,3921753
1030,DDoS-UDP_Flood.pcap,DC:A6:32:C9:E4:D5,"0.0.0.0, 192.168.137.224, 192.168.137.233, fe8...",3817861,741,3818602
1031,DDoS-UDP_Flood.pcap,DC:A6:32:C9:E5:A4,"192.168.137.96, fe80::dea6:32ff:fec9:e5a4",3602215,1060,3603275
1124,DDoS-UDP_Fragmentation.pcap,DC:A6:32:C9:E4:90,"192.168.137.17, fd5a:7bd:2aea:e111:dea6:32ff:f...",740646,1328,741974
1125,DDoS-UDP_Fragmentation.pcap,DC:A6:32:C9:E4:D5,"0.0.0.0, 192.168.137.20, fd5a:7bd:2aea:e111:de...",547063,1339,548402
1127,DDoS-UDP_Fragmentation.pcap,DC:A6:32:C9:E5:EF,192.168.137.42,291401,1117,292518
1128,DDoS-UDP_Fragmentation.pcap,DC:A6:32:C9:E4:AB,"192.168.137.212, fd5a:7bd:2aea:e111:dea6:32ff:...",234487,1159,235646
1130,DDoS-UDP_Fragmentation.pcap,DC:A6:32:DC:27:D5,"192.168.137.65, fd5a:7bd:2aea:e111:dea6:32ff:f...",119249,1435,120684

## 2단계: 카메라가 실제 피해 기기인지 확인하기

## 3단계 rf용 대이터는 따로 준비하기:

### 3방법 a공식 CICIoT2023csv파일 사용 -> 이미 pcap에서 ml특징 추출한 csv가 있고 공식 페이지에서도 이 csv를 ml평가용으로 함

우리 PCAP
→ 기기별 네트워크 분석용

공식 CSV
→ RF 학습용

으로 역할 나누기.

###3방법b 우리가 PCAP에서 직접 feature extraction

직접 flow_duration,
Rate,
Srate,
Drate,
IAT,
syn_count,
ack_count,
packet length statistics,
...
를 계산해야하고 공식 피쳐 extraction과 동일한 윈도우 정의까지 재현해야하는데 비효율적

In [22]:

# RF 넘어가기전 앞서 만든 analyze_pcap_devices()를 12개에 돌린 뒤, 아래 세 결과 뽑기

# 1. 파일별 total_packets TOP 5

top_total = (
    all_devices_df
    .sort_values(
        ["file", "total_packets"],
        ascending=[True, False]
    )
    .groupby("file")
    .head(5)
)


# 2. 파일별 received_packets TOP 5

top_received = (
    all_devices_df
    .sort_values(
        ["file", "received_packets"],
        ascending=[True, False]
    )
    .groupby("file")
    .head(5)
)


# 3. 파일별 sent_packets TOP 5

top_sent = (
    all_devices_df
    .sort_values(
        ["file", "sent_packets"],
        ascending=[True, False]
    )
    .groupby("file")
    .head(5)
)

In [23]:
file_name = "DDoS-SYN_Flood.pcap"

all_devices_df[
    all_devices_df["file"] == file_name
][
    [
        "mac",
        "ips",
        "sent_packets",
        "received_packets",
        "total_packets",
        "top_peer"
    ]
].sort_values(
    "received_packets",
    ascending=False
).head(20)

,mac,ips,sent_packets,received_packets,total_packets,top_peer
632,1C:12:B0:9B:0C:EC,"0.0.0.0, 192.168.137.99, ::, fe80::1e12:b0ff:f...",170629,8786693,8957322,DC:A6:32:C9:E4:AB
633,1C:FE:2B:98:16:DD,"0.0.0.0, 192.168.137.30",223059,7655917,7878976,DC:A6:32:C9:E4:AB
635,CC:F4:11:9C:D0:00,"0.0.0.0, 192.168.137.12, ::, fe80::cef4:11ff:f...",5618,6701211,6706829,DC:A6:32:C9:E4:AB
641,9C:8E:CD:1D:AB:9F,192.168.137.161,14686,2870769,2885455,DC:A6:32:C9:E4:AB
634,DC:A6:32:C9:E4:AB,"192.168.137.240, fe80::dea6:32ff:fec9:e4ab",7079462,87516,7166978,1C:12:B0:9B:0C:EC
642,3C:18:A0:41:C3:A0,"1.1.1.1, 100.20.126.204, 100.20.212.253, 100.2...",81589,75973,157562,AC:17:02:05:34:27
636,DC:A6:32:DC:27:D5,"192.168.137.17, fe80::dea6:32ff:fedc:27d5",4307275,70868,4378143,1C:12:B0:9B:0C:EC
637,DC:A6:32:C9:E4:90,192.168.137.195,4163427,64320,4227747,1C:FE:2B:98:16:DD
638,E4:5F:01:55:90:C4,192.168.137.134,3827597,60845,3888442,1C:FE:2B:98:16:DD
639,DC:A6:32:C9:E5:EF,"192.168.137.58, fe80::dea6:32ff:fec9:e5ef",3659456,56798,3716254,1C:FE:2B:98:16:DD
640,DC:A6:32:C9:E4:D5,"192.168.137.224, fe80::dea6:32ff:fec9:e4d5",2963457,55251,3018708,1C:12:B0:9B:0C:EC
644,FF:FF:FF:FF:FF:FF,255.255.255.255,0,27895,27895,1C:FE:2B:98:16:DD
643,AC:17:02:05:34:27,192.168.137.94,20120,19801,39921,3C:18:A0:41:C3:A0
645,A0:D0:DC:C4:08:FF,192.168.137.14,6847,4350,11197,2C:71:FF:05:F1:15
646,7C:78:B2:86:0D:81,"0.0.0.0, 192.168.137.128",4660,4012,8672,3C:18:A0:41:C3:A0
647,EE:06:3B:B8:D1:DF,"192.168.137.208, fe80::1c22:89ec:2941:f3a6",4158,3831,7989,3C:18:A0:41:C3:A0
649,08:7C:39:CE:6E:2A,"0.0.0.0, 192.168.137.247, ::, fe80::a7c:39ff:f...",3286,3214,6500,3C:18:A0:41:C3:A0
650,40:5D:82:35:14:C8,192.168.137.174,3330,3090,6420,3C:18:A0:41:C3:A0
651,6C:5A:B0:44:1D:90,192.168.137.6,3006,2997,6003,3C:18:A0:41:C3:A0
648,10:2C:6B:1B:43:BE,192.168.137.81,3587,2926,6513,3C:18:A0:41:C3:A0

# 결과저장 폴더 만들기
이미 결과 CSV가 있는 PCAP은 자동으로 건너뜀

In [24]:
from pathlib import Path

RESULT_DIR = PCAP_DIR / "analysis_results"
RESULT_DIR.mkdir(exist_ok=True)

print(RESULT_DIR)

/content/drive/MyDrive/CICIoT2023/analysis_results

In [25]:
import pandas as pd

for i, file in enumerate(pcap_files, start=1):

    output_file = RESULT_DIR / f"{file.stem}_device_summary.csv"

    print(f"\n[{i}/{len(pcap_files)}] {file.name}")

    # 이미 분석 결과가 있으면 건너뛰기
    if output_file.exists():
        print("→ 이미 분석 완료. 건너뜀")
        continue

    print("→ 분석 시작")

    total_packets, temp_df = analyze_pcap_devices(file)

    temp_df["file"] = file.name
    temp_df["pcap_total_packets"] = total_packets

    # 분석 직후 즉시 저장
    temp_df.to_csv(
        output_file,
        index=False
    )

    print("→ 분석 완료")
    print("패킷 수:", f"{total_packets:,}")
    print("저장:", output_file)

[1/12] DDoS-ACK_Fragmentation.pcap
→ 이미 분석 완료. 건너뜀

[2/12] DDoS-HTTP_Flood-.pcap
→ 이미 분석 완료. 건너뜀

[3/12] DDoS-ICMP_Flood.pcap
→ 이미 분석 완료. 건너뜀

[4/12] DDoS-ICMP_Fragmentation.pcap
→ 이미 분석 완료. 건너뜀

[5/12] DDoS-PSHACK_Flood.pcap
→ 이미 분석 완료. 건너뜀

[6/12] DDoS-RSTFINFlood.pcap
→ 이미 분석 완료. 건너뜀

[7/12] DDoS-SYN_Flood.pcap
→ 이미 분석 완료. 건너뜀

[8/12] DDoS-SlowLoris.pcap
→ 이미 분석 완료. 건너뜀

[9/12] DDoS-SynonymousIP_Flood.pcap
→ 이미 분석 완료. 건너뜀

[10/12] DDoS-TCP_Flood.pcap
→ 이미 분석 완료. 건너뜀

[11/12] DDoS-UDP_Flood.pcap
→ 이미 분석 완료. 건너뜀

[12/12] DDoS-UDP_Fragmentation.pcap
→ 이미 분석 완료. 건너뜀

In [30]:
all_results = []

for file in result_files:
    df_temp = pd.read_csv(file)
    all_results.append(df_temp)

all_devices_df = pd.concat(
    all_results,
    ignore_index=True
)

print(all_devices_df.shape)

all_devices_df.head()

NameError: name 'result_files' is not defined

In [28]:
all_devices_df.to_csv(
    RESULT_DIR / "all_devices_summary.csv",
    index=False
)

## 다시 분석 안하게 저장해둬서 다음번 코랩에서는 다음 코드만 실행하면됨


`all_devices_df.to_csv(
    RESULT_DIR / "all_devices_summary.csv",
    index=False
)`